# Site settings
title: Abimael Martinez
email: abijr.mtz [ @ ] gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about programming things, and stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://abijr.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  abijr

# Build settings
markdown: kramdown
